### ISSUE TITLE
Potential collaboration

### ISSUE THREAD

**Issue by brianprichardson** [crypt3lx2k/Zerofish#1]
See here:
[https://github.com/Zeta36/chess-alpha-zero](url)

**Comment by brianprichardson** [comment]
Still new to GitHub but copying and pasting link works whereas just clicking does not.

**Comment by Akababa** [comment]
https://github.com/Zeta36/chess-alpha-zero

**Comment by crypt3lx2k** [comment]
I'm aware of that project, I think it's better to have multiple independent projects running until someone gets something that's working well.
