### ISSUE TITLE
/tmp/zf 

### ISSUE THREAD

**Issue by brianprichardson** [crypt3lx2k/Zerofish#2]
Ran endgame branch for several days and re-booted last night.  I am quite new to Ubuntu but perhaps there is a better place for the best model than /tmp/zf (/var/tmp?), or it might be someplace else that I cannot find.
Thanks,
Brian

PS  endgame git clone did not download actual endgame branch but .zip download did.  Is this how GitHub works (I'm also new to GitHub)

**Comment by 8269437145** [comment]
/tmp/ just gives you assurance that the training data is volatile. if you think it was successful and want to save it , then you can just move it then. otherwise , it will just be lost.

https://stackoverflow.com/a/4438292

**Comment by crypt3lx2k** [comment]
Hey Brian,
I'm working on improving the code-base now so that the experiments will be easier to run. When you git clone you'll have to do "git checkout endgame" in the cloned repo to get to the endgame branch.

I'll be updating my post on talkchess before the end of the week with some results.

**Comment by crypt3lx2k** [comment]
Storing the data in /tmp is just because that's (in my experience) usually local to the machine in case you run this on some computing service.
